services:
  oct-server:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: oct/oct-server
    ports:
      - 8100:8100
    container_name: oct-server
    enviroments:
      - OCT_ACTIVATE_SIMPLE_LOGIN=$OCT_ACTIVATE_SIMPLE_LOGIN
      - OCT_BASE_URL=$OCT_BASE_URL
      - OCT_JWT_PRIVATE_KEY=$OCT_JWT_PRIVATE_KEY
      - OCT_OAUTH_GITHUB_CLIENTID=$OCT_OAUTH_GITHUB_CLIENTID
      - OCT_OAUTH_GITHUB_CLIENTSECRET=$OCT_OAUTH_GITHUB_CLIENTSECRET
      - OCT_SERVER_OWNER=$OCT_SERVER_OWNER